ActOS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

app_name = 'ActOS'

urlpatterns = [
    path('', views.login_page, name='index'),
    path('home/', views.home_page, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('ActOS/', include('Core.urls')),
    path('admin/', admin.site.urls),
]

handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .forms import *

app_name = 'Core'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('InputAct/', views.input_activity),
    path('prj/', views.ProjectIndexView.as_view(), name='project_index'),
    path('prj/cr/', views.ProjectCreateView.as_view(), name='project_create'),
    path('prj/up/<slug:slug>', views.ProjectUpdateView.as_view(),
         name='project_update'),
    path('prj/del/<slug:slug>', views.ProjectDeleteView.as_view(),
         name='project_delete'),
    path('tsk/', views.TaskIndexView.as_view(), name='task_index'),
    path('tsk/<int:pk>', views.ProjectTaskDetailView.as_view(), name='task_detail'),
    path('tsk/cr/<int:ID_Project>',
         views.ProjectTaskCreateView.as_view(), name='task_create'),
    path('tsk/up/<int:pk>', views.ProjectTaskUpdateView.as_view(),
         name='task_update'),
    path('tsk/del/<int:pk>', views.ProjectTaskDeleteView.as_view(),
         name='task_delete'),
    path('asgnmnt/cr/<int:pid>', views.ProjectAssignmentCreateView.as_view(),
         name='assignment_create'),
    path('asgnmnt/', views.AssignmentIndexView.as_view(),
         name='assignment_index'),
    path('asgnmnt/pr/<int:pid>/detail', views.ProjectAssignmentDetailView.as_view(),
         name='assignment_detail'),
    path('actlog/', views.ActivityLogIndexView.as_view(), name='activity_index'),

]

Core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django.utils.text import slugify
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import datetime, timedelta, date

# Create your models here.


class Personnel (models.Model):
    ID_Personnel = models.IntegerField(primary_key=True, default=0)  # - INT
    First_Name = models.CharField(max_length=20)  # - CHAR 20
    Last_Name = models.CharField(max_length=20)  # - CHAR 20
    Position = models.CharField(max_length=20)  # - CHAR 20)
    Personnel_status = [
        ('E', 'Employee'),
        ('O', 'Outsource'),
        ('C', 'Contract')
    ]
    Status = models.CharField(
        max_length=2,
        choices=Personnel_status,
        default='E'
    )

    def __str__(self):
        fname = '%s ' % self.First_Name
        lname = '%s ' % self.Last_Name
        fullname = fname + lname
        return fullname


class Customer(models.Model):
    ID_Customer = models.AutoField(primary_key=True)
    Customer_Name = models.CharField(max_length=50)


class Vendor(models.Model):
    ID_Vendor = models.AutoField(primary_key=True)
    Vendor_Name = models.CharField(max_length=50)


class Project(models.Model):
    ID_Project = models.AutoField(primary_key=True)
    Title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    Description = models.TextField(blank=True)
    # Project_Manager = models.ForeignKey(
    #     to=Personnel, on_delete=models.DO_NOTHING, default=0, null=True)
    Total_Mandays = models.IntegerField(blank=False, default=0)
    Start_Date = models.DateField(blank=False)
    End_Date = models.DateField(blank=False)
    Created_On = models.DateTimeField(auto_now_add=True)
    Last_Update = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.Title)
        super(Project, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('Core:project_index')

    def __str__(self):
        return '%s' % self.Title


class ProjectTask(models.Model):
    ID_Task = models.AutoField(primary_key=True)
    ID_Project = models.ForeignKey(
        'Project', on_delete=models.CASCADE, related_name='task')
    Priority_level = [
        ('H', 'HIGH'),
        ('M', 'MEDIUM'),
        ('L', 'LOW')
    ]
    Priority = models.CharField(
        max_length=10, choices=Priority_level, default='M')
    Title = models.CharField(max_length=255)
    Description = models.TextField(blank=True)
    Task_status = [
        ('OG', 'On-Going'),
        ('DN', 'Done'),
        ('PD', 'Pending')
    ]
    Status = models.CharField(max_length=2, choices=Task_status, default='OG')
    PctComplete = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])
    PctWeight = models.FloatField(
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])
    Start_Date = models.DateField(blank=False)
    TargetFinish_Date = models.DateField(blank=False)
    Target_Duration = models.IntegerField(default=0)
    Created_On = models.DateTimeField(auto_now_add=True)
    Last_Update = models.DateTimeField(auto_now=True)
    # consisting list of ID_Personnel separated by ','
    PIC = models.CharField(max_length=255)
    Total_Mandays = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        # subject to Re-Check / Validate Result of Target_Duration
        d1 = date.fromisoformat(str(self.Start_Date))
        d2 = date.fromisoformat(str(self.TargetFinish_Date))
        delta = d2-d1
        self.Target_Duration = delta.days
        self.Total_Mandays = len(
            str.split(self.PIC, ',')) * self.Target_Duration
        super(ProjectTask, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('Core:task_index')

    def __str__(self):
        return self.Title


class ProjectAssignment(models.Model):
    ID_Personnel = models.ForeignKey(
        to='Personnel', on_delete=models.PROTECT, related_name='assigned_project')
    ID_Project = models.ForeignKey(
        to='Project', on_delete=models.PROTECT, related_name='assigned_team')
    is_PM = models.BooleanField(default=False)
    Start_Date = models.DateField(blank=False)
    End_Date = models.DateField(blank=False)
    Created_On = models.DateTimeField(auto_now_add=True)
    Last_Update = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('Core:assignment_index')

    def __str__(self):
        return self.ID_Project.Title


class ActivityLog(models.Model):
    ID_Activity = models.AutoField(primary_key=True)
    Activity_Date = models.DateField(blank=False, unique=True)
    ID_Personnel = models.ForeignKey(to='Personnel', on_delete=models.CASCADE)
    ID_Assignment = models.ForeignKey(
        to='ProjectAssignment', on_delete=models.CASCADE, related_name='assignment')
    ID_ProjectTask = models.ForeignKey(
        to='ProjectTask', on_delete=models.DO_NOTHING)
    Description = models.TextField(blank=True)
    Loc_Options = [
        ('R', 'Remote'),
        ('O', 'Office'),
        ('C', 'Customer Site')
    ]
    Location = models.CharField(max_length=1, choices=Loc_Options, default='O')
    is_Approve = models.BooleanField(default=False)
    Created_On = models.DateTimeField(auto_now_add=True)
    Last_Update = models.DateTimeField(auto_now=True)


# class DetailActivity(models.Model):
#     ID_ProjectTask = models.ForeignKey(
#         to='ProjectTask', on_delete=models.DO_NOTHING)
#     ID_Activity = models.ForeignKey(to='ActivityLog', on_delete=models.CASCADE)
#     Description = models.CharField(max_length=500)
#     Loc_Options = [
#         ('R', 'Remote'),
#         ('O', 'Office'),
#         ('C', 'Customer Site')
#     ]
#     Location = models.CharField(max_length=1, choices=Loc_Options, default='O')
#     PctTaskComplete = models.FloatField(
#         validators=[MinValueValidator(0.0), MaxValueValidator(100.0)])
#     Created_On = models.DateTimeField(auto_now_add=True)
#     Last_Update = models.DateTimeField(auto_now=True)


class UserPersonnel(models.Model):
    ID_User = models.OneToOneField(User, on_delete=models.CASCADE)
    ID_Personnel = models.ForeignKey(Personnel, on_delete=models.CASCADE)

Core/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.http import request, HttpRequest


class PersonnelForm (ModelForm):
    class Meta:
        model = Personnel
        fields = ['ID_Personnel', 'First_Name',
                  'Last_Name', 'Position', 'Status']


class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ['ID_Customer', 'Customer_Name']


class VendorForm(ModelForm):
    class Meta:
        model = Vendor
        fields = ['ID_Vendor', 'Vendor_Name']


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['Title',
                  'Description', 'Start_Date', 'End_Date']
        widgets = {
            'Description': forms.Textarea,
        }


class ProjectTaskForm(ModelForm):
    class Meta:
        model = ProjectTask
        fields = ['Title', 'Priority', 'Description', 'Status',
                  'PctComplete', 'PctWeight', 'Start_Date', 'TargetFinish_Date', 'PIC'
                  ]


class ProjectAssignmentForm(ModelForm):
    class Meta:
        model = ProjectAssignment
        fields = ['ID_Personnel',
                  'is_PM', 'Start_Date', 'End_Date']
        label = ['Personnel', 'as a PM ?', 'Start_Date', 'End_Date']


class ActivityLogForm(ModelForm):
    class Meta:
        model = ActivityLog
        fields = ['Activity_Date',
                  'ID_Assignment', 'ID_ProjectTask', 'Location', 'Description']

    # def __init__(self, *args, **kwargs):
    #     super(ActivityLogForm, self).__init__(*args, **kwargs)
    #     personnel = UserPersonnel.objects.get(ID_User=HttpRequest.user)
    #     projects = ProjectAssignment.objects.filter(ID_Personnel=personnel)
    #     tasks = ProjectTask.objects.filter(ID_Projects=projects)
    #     self.fields['ID_ProjectTask'].queryset = tasks

# class DetailActivityForm(ModelForm):
#     class Meta:
#         model = DetailActivity
#         fields = ['ID_ProjectTask', 'ID_Activity',
#                   'Description', 'Location', 'PctTaskComplete']

Core/views.py
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, DeleteView,
                                  UpdateView)
from . import models
from django.http import HttpResponse, HttpResponseRedirect
# from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.utils import timezone
from .forms import *
from ActOS import views
from django.urls import reverse_lazy

# Create your views here.


def home_page(request):

    return views.home_page(request)


def input_activity(request):
    link = 'forms/inputAct.html'
    if request.user.is_authenticated:
        # act_filter = ActivityLogFilter(request.GET, queryset=task)
        context = views.get_user_context(request)
        # context['filter'] = act_filter
        return add_model_form(request, ActivityLogForm, link, context)
    return home_page(request)


def add_model_form(request, model_form, template_link, contexts):
    if request.user.is_authenticated:
        obj_user = User.objects.get(username=request.user.username)
        obj_UserPerson = UserPersonnel.objects.get(ID_User=obj_user.id)
        idp = int(obj_UserPerson.ID_Personnel_id)
        obj_personnel = Personnel.objects.get(
            ID_Personnel=idp)
        context = {}
        context['fname'] = obj_personnel.First_Name
        context['lname'] = obj_personnel.Last_Name
        if request.method == "POST":
            form = model_form(request.POST)
            if form.is_valid():
                model_instance = form.save(commit=False)
                model_instance.timestamp = timezone.now()
                model_instance.save()
                return redirect('/')

        else:

            form = model_form()
            context['form'] = form
            # context['filter'] = contexts['filter']
            return render(request, template_link, context)
    return render(request, 'registration/login.html')


# -------------- CBV - class based views
class ProjectIndexView(TemplateView):
    template_name = 'Core/Project_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(views.get_user_context(self.request))

        # projects = Project.objects.all()
        # project_tasks = {}
        # for p in projects:
        #     idx = p.ID_Project
        #     project_tasks[idx] = ProjectTask.objects.filter(ID_Project=idx)
        # context['Projects'] = projects
        # context['Tasks'] = project_tasks

        # context[""] =
        return context


class ProjectCreateView(CreateView):
    # fields = ('Title', 'Description', 'Total_Mandays',
    #           'Start_Date', 'End_Date')
    model = Project
    form_class = ProjectForm


class ProjectUpdateView(UpdateView):
    fields = ('Title', 'Description', 'Total_Mandays',
              'Start_Date', 'End_Date')
    model = Project


class ProjectDeleteView(DeleteView):
    model = Project
    success_url = reverse_lazy('Core:project_index')


class TaskIndexView(TemplateView):
    template_name = 'Core/projecttask_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(views.get_user_context(self.request))

        # projects = Project.objects.all()
        # project_tasks = {}
        # progress = {}
        # for p in projects:
        #     progress[p.ID_Project] = ProjectProgress(p.ID_Project)
        #     idx = p.ID_Project
        #     project_tasks[idx] = ProjectTask.objects.filter(ID_Project=idx)
        # context['Projects'] = projects
        # context['Tasks'] = project_tasks
        # context['Progress'] = progress

        # context[""] =
        return context


class ProjectTaskDetailView(DetailView):
    model = ProjectTask
    template_name = 'Core/projecttask_detail.html'
    context_object_name = 'projecttask_detail'


class ProjectTaskCreateView(CreateView):
    # fields = ('Title', 'Description', 'Total_Mandays',
    #           'Start_Date', 'End_Date')
    model = ProjectTask
    form_class = ProjectTaskForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.ID_Project = Project.objects.get(
            ID_Project=self.kwargs['ID_Project'])
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class ProjectTaskUpdateView(UpdateView):
    model = ProjectTask
    form_class = ProjectTaskForm


class ProjectTaskDeleteView(DeleteView):
    model = ProjectTask
    success_url = reverse_lazy('Core:task_index')

# --------------- PROJECT ASSIGNMENT


class AssignmentIndexView(TemplateView):
    template_name = 'Core/projectassignment_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(views.get_user_context(self.request))

        projects = context['Projects']
        assigned_personnel = {}
        for p in projects:
            try:
                assigned_personnel[p.ID_Project] = ProjectAssignment.objects.all().filter(
                    ID_Project=p.ID_Project)
            except:
                print('error when query data to project assignment')
        context['Projects'] = projects
        context['Assignment'] = assigned_personnel
        return context


class ProjectAssignmentDetailView(DetailView):
    model = ProjectAssignment
    template_name = 'Core/projectassignment_detail.html'
    context_object_name = 'projectassignment_detail'


class ProjectAssignmentCreateView(CreateView):
    # fields = ('Title', 'Description', 'Total_Mandays',
    #           'Start_Date', 'End_Date')
    model = ProjectAssignment
    form_class = ProjectAssignmentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['Project'] = Project.objects.get(
                ID_Project=self.kwargs['pid'])
        except:
            print(
                f'Project Assignment Create : Error Retrieving Project where  ID_Project = {self.kwargs["pid"]}')
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.ID_Project = Project.objects.get(
            ID_Project=self.kwargs['pid'])
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


# class ProjectAssignmentUpdateView(UpdateView):
#     model = ProjectAssignment
#     form_class = ProjectAssignmentForm

class ActivityLogIndexView(TemplateView):
    template_name = 'Core/activitylog_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(views.get_user_context(self.request))
        return context

templates/Core/Project_index.html
{% extends "base.html" %}
{% load dict_filter %}

{% block title %} Project Administration {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Projects Administration</h3>
            </div>
        </div>
        <div class="title_right">
            <a href="{% url 'Core:project_create' %}" class="btn btn-primary">Create New Project</a>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                {% for p in Projects %}
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Projects - {{ p.Title }}</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a href="{% url 'Core:project_update' slug=p.slug %}" class="btn btn-default">Edit</a>
                            </li>
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <br>
                        <br>
                        <div class="progress progress_sm">
                            <div class="progress-bar bg-blue" role="progressbar"
                                data-transitiongoal="{{ Progress|lookup:p.ID_Project }}">
                            </div>
                        </div>
                        <small>{{ Progress|lookup:p.ID_Project }}% Complete</small>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">
                            <p>Project : {{ p.Title }}</p>
                            <p>Description : {{ p.Description }}</p>
                            <p>Start : {{ p.Start_Date }}</p>
                            <p>Finish : {{ p.End_Date }}</p>
                            <p>Total Mandays : {{ p.Total_Mandays }}</p>
                            <p class='small'>last update : {{ p.Last_Update }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock content %}

    {% block javascripts %}
    {{ block.super }}
    <!-- morris.js -->
    <script src="/static/vendors/raphael/raphael.min.js"></script>
    <script src="/static/vendors/morris.js/morris.min.js"></script>
    {% endblock javascripts %}

templates/Core/projectassignment_index.html
{% extends "base.html" %}
{% load dict_filter %}


{% block title %} Project Assignment {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Projects Assignment</h3>
            </div>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                {% for p in Projects %}
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Projects - {{ p.Title }}</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">
                            <p class="emphasis">Project : {{ p.Title }}</p>
                            <p class="emphasis">Description : {{ p.Description }}</p>
                            <p class="emphasis"><strong>Personnel Assigned : </strong></p>
                            <!-- START LOOP PERSONNEL -->
                            <ul class="list-inline">
                                {% for pasgn in Assignment|lookup:p.ID_Project %}
                                <li>
                                    <div class="container">
                                        <span class="btn btn-round btn-default btn-md">
                                            <div class="col-sm-6">
                                                <div class="left col-xs-3">
                                                    <h4>{{ pasgn.ID_Personnel }}
                                                        <!--  -->
                                                    </h4>
                                                    <p><strong>Role: </strong> {{ pasgn.ID_Personnel.Position }}</p>
                                                    <button type="button" class="btn btn-primary btn-xs">
                                                        <i class="fa fa-tasks"> </i> View Activity Log
                                                    </button>
                                                </div>
                                            </div>
                                        </span>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>

                            <!-- END LOOP PERSONNEL -->
                        </div>
                        <a href="{% url 'Core:assignment_create' pid=p.ID_Project %}" class="btn btn-primary"><i
                                class="fa fa-users"></i> Add Personnel Assignment</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock content %}

    {% block javascripts %}
    {{ block.super }}
    <!-- morris.js -->
    <script src="/static/vendors/raphael/raphael.min.js"></script>
    <script src="/static/vendors/morris.js/morris.min.js"></script>
    {% endblock javascripts %}

templates/Core/projecttask_index.html
{% extends "base.html" %}
{% load dict_filter %}

{% block title %} Home {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Task Administration</h3>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                {% for p in Projects %}
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Projects - {{ p.Title }}
                        </h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <br>
                        <br>
                        <div class="progress progress_sm">
                            <div class="progress-bar bg-blue" role="progressbar"
                                data-transitiongoal="{{ Progress|lookup:p.ID_Project }}">
                            </div>
                        </div>
                        <small>{{ Progress|lookup:p.ID_Project }}% Complete</small>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <p>{{ p.Description }}</p>

                        <!-- start project list -->

                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 1%">#</th>
                                    <th style="width: 20%">Task</th>
                                    <th>Priority</th>
                                    <th>PIC</th>
                                    <th>Weight</th>
                                    <th>Project Progress</th>
                                    <th>Status</th>
                                    <th style="width: 20%">#Edit</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% comment %} {% for k, v in Tasks.items %} {% endcomment %}
                                {% comment %} {% for t in v %} {% endcomment %}
                                {% for t in Tasks|lookup:p.ID_Project %}

                                <tr>
                                    <td>#</td>
                                    <td>
                                        <a href="{{t.ID_Task}}">{{ t.Title }}</a>
                                        <br />
                                        <small>Created On {{ t.Created_On|date:"d M Y" }}</small>
                                    </td>
                                    {% if t.Priority == 'H' %}
                                    <td><span class="label label-danger">High</span></td>
                                    {% elif t.Priority == 'M' %}
                                    <td><span class="label label-warning">Medium</span></td>
                                    {% else %}
                                    <td><span class="label label-info">Low</span></td>
                                    {% endif %}
                                    <td>
                                        <ul class="list-inline">
                                            {% for pic in t.PIC|splitby:','  %}
                                            <li>
                                                <span class="btn btn-primary btn-xs">{{ pic }}</span>
                                            </li>
                                            {% endfor %}
                                            {% comment %} <li>
                                                <img src="/static/images/user.png" class="avatar" alt="Avatar">
                                            </li>
                                            <li>
                                                <img src="/static/images/user.png" class="avatar" alt="Avatar">
                                            </li>
                                            <li>
                                                <img src="/static/images/user.png" class="avatar" alt="Avatar">
                                            </li> {% endcomment %}

                                        </ul>
                                    </td>
                                    <td>
                                        {{t.PctWeight|floatformat:0}}
                                    </td>
                                    <td class="project_progress">
                                        <div class="progress progress_sm">
                                            <div class="progress-bar bg-green" role="progressbar"
                                                data-transitiongoal="{{ t.PctComplete }}">
                                            </div>
                                        </div>
                                        <small>{{ t.PctComplete|floatformat:0 }}% Complete</small>
                                    </td>
                                    <td>
                                        {% if t.Status == 'OG' %}
                                        <button type="button" class="btn btn-success btn-xs">On-Going</button>
                                        {% elif t.Status == 'PD' %}
                                        <button type="button" class="btn btn-success btn-xs">Pending</button>
                                        {% else %}
                                        <button type="button" class="btn btn-success btn-xs">Done</button>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <a href="{% url 'Core:task_update' pk=t.ID_Task %}"
                                            class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                                        <a href="#" class="btn btn-success btn-xs"><i class="fa fa-line-chart"></i>
                                            Update Progress
                                        </a>
                                        <a href="{% url 'Core:task_delete' pk=t.ID_Task %}"
                                            class=" btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete
                                        </a>
                                    </td>
                                </tr>

                                {% comment %} {% endfor %} {% endcomment %}
                                {% endfor %}
                            </tbody>
                        </table>
                        <a href="{% url 'Core:task_create' ID_Project=p.ID_Project %}" class="btn btn-primary btn-xs"><i
                                class="fa fa-file-o"></i> Add New Task </a>
                        <!-- end project list -->
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock content %}

    {% block javascripts %}
    {{ block.super }}
    <!-- morris.js -->
    <script src="/static/vendors/raphael/raphael.min.js"></script>
    <script src="/static/vendors/morris.js/morris.min.js"></script>
    {% endblock javascripts %}