ActOS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views

app_name = 'ActOS'

urlpatterns = [
    path('', views.login_page, name='index'),
    path('home/', views.home_page, name='home'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('ActOS/', include('Core.urls')),
    path('admin/', admin.site.urls),
]

handler404 = views.handler404
handler500 = views.handler500

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .forms import *

app_name = 'Core'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('InputAct/', views.input_activity),
    path('prj/', views.ProjectIndexView.as_view(), name='project_index'),
    path('prj/cr/', views.ProjectCreateView.as_view(), name='project_create'),
    path('prj/up/<slug:slug>', views.ProjectUpdateView.as_view(),
         name='project_update'),
    path('prj/del/<slug:slug>', views.ProjectDeleteView.as_view(),
         name='project_delete'),
    path('tsk/', views.TaskIndexView.as_view(), name='task_index'),
    path('tsk/<int:pk>', views.ProjectTaskDetailView.as_view(), name='task_detail'),
    path('tsk/cr/<int:ID_Project>',
         views.ProjectTaskCreateView.as_view(), name='task_create'),
    path('tsk/up/<int:pk>', views.ProjectTaskUpdateView.as_view(),
         name='task_update'),
    path('tsk/del/<int:pk>', views.ProjectTaskDeleteView.as_view(),
         name='task_delete'),
    path('asgnmnt/cr/<int:pid>', views.ProjectAssignmentCreateView.as_view(),
         name='assignment_create'),
    path('asgnmnt/', views.AssignmentIndexView.as_view(),
         name='assignment_index'),
    path('asgnmnt/pr/<int:pid>/detail', views.ProjectAssignmentDetailView.as_view(),
         name='assignment_detail'),
    path('actlog/', views.ActivityLogIndexView.as_view(), name='activity_index'),

]

templates/Project_index.html
{% extends "base.html" %}
{% load dict_filter %}

{% block title %} Project Administration {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Projects Administration</h3>
            </div>
        </div>
        <div class="title_right">
            <a href="{% url 'Core:project_create' %}" class="btn btn-primary">Create New Project</a>
        </div>
        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">

                {% for p in Projects %}
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Projects - {{ p.Title }}</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a href="{% url 'Core:project_update' pk=p.ID_Project%}"
                                    class="btn btn-default">Edit</a>
                            </li>
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="container">
                            <p>Project : {{ p.Title }}</p>
                            <p>Description : {{ p.Description }}</p>
                            <p>Start : {{ p.Start_Date }}</p>
                            <p>Finish : {{ p.End_Date }}</p>
                            <p class='small'>last update : {{ p.Last_Update }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endblock content %}

    {% block javascripts %}
    {{ block.super }}
    <!-- morris.js -->
    <script src="/static/vendors/raphael/raphael.min.js"></script>
    <script src="/static/vendors/morris.js/morris.min.js"></script>
    {% endblock javascripts %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>ActOS | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        {% comment %} <link href="/static/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}
        <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static 'vendors/iCheck/skins/flat/green.css' %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}" rel="stylesheet">
        <!-- JQVMap -->
        <link href="{% static 'vendors/jqvmap/dist/jqvmap.min.css' %}" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="{% static 'build/css/custom.css' %}" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block top_navigation %}
            <div class="top_nav">
              {% include "top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block content %}
            <!-- {{ content }} -->
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
        <!-- Bootstrap -->
        <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <!-- FastClick -->
        <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
        <!-- NProgress -->
        <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
        <!-- iCheck -->
        <script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="{% static 'vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js' %}"></script>
        <script src="{% static 'vendors/jquery.hotkeys/jquery.hotkeys.js' %}"></script>
        <script src="{% static 'vendors/google-code-prettify/src/prettify.js' %}"></script>
        <!-- jQuery Tags Input -->
        <script src="{% static 'vendors/jquery.tagsinput/src/jquery.tagsinput.js' %}"></script>
        <!-- Switchery -->
        <script src="{% static 'vendors/switchery/dist/switchery.min.js' %}"></script>
        <!-- Select2 -->
        <script src="{% static 'vendors/select2/dist/js/select2.full.min.js' %}"></script>
        <!-- Parsley -->
        <script src="{% static 'vendors/parsleyjs/dist/parsley.min.js' %}"></script>
        <!-- Autosize -->
        <script src="{% static 'vendors/autosize/dist/autosize.min.js' %}"></script>
        <!-- jQuery autocomplete -->
        <script src="{% static 'vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js' %}"></script>
        <!-- starrr -->
        <script src="{% static 'vendors/starrr/dist/starrr.js' %}"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="{% static 'build/js/custom.js' %}"></script>
    {% endblock body %}
  </body>
</html>

templates/footer.html
<div class="pull-right">
  &copy; Copyright 2019 CKS - KHO
</div>
<div class="clearfix"></div>

templates/homepage.html
{% extends "base.html" %}
{% load dict_filter %}

{% block title %} Home {% endblock title %}

{% block stylesheets %}
{{ block.super }}
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Activity Workbench</h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        {% for p in Projects %}
        <div class="x_panel">
          <div class="x_title">
            <h2>Projects - {{ p.Title }}</h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">

            <p>{{ p.Description }}</p>

            <!-- start project list -->

            <table class="table table-striped projects">
              <thead>
                <tr>
                  <th style="width: 1%">#</th>
                  <th style="width: 20%">Task</th>
                  <th>Priority</th>
                  <th>PIC</th>
                  <th>Project Progress</th>
                  <th>Status</th>
                  <th style="width: 20%">#Edit</th>
                </tr>
              </thead>
              <tbody>
                {% comment %} {% for k, v in Tasks.items %} {% endcomment %}
                {% comment %} {% for t in v %} {% endcomment %}
                {% for t in Tasks|lookup:p.ID_Project %}

                <tr>
                  <td>#</td>
                  <td>
                    <a href="{{t.ID_Task}}">{{ t.Title }}</a>
                    <br />
                    <small>Created On {{ t.Created_On|date:"d M Y" }}</small>
                  </td>
                  {% if t.Priority == 'H' %}
                  <td><span class="label label-danger">High</span></td>
                  {% elif t.Priority == 'M' %}
                  <td><span class="label label-warning">Medium</span></td>
                  {% else %}
                  <td><span class="label label-info">Low</span></td>
                  {% endif %}
                  <td>
                    <ul class="list-inline">
                      {% for pic in t.PIC|splitby:','  %}
                      <li>
                        <span class="btn btn-primary btn-xs">{{ pic }}</span>
                      </li>
                      {% endfor %}
                      {% comment %} <li>
                        <img src="/static/images/user.png" class="avatar" alt="Avatar">
                      </li>
                      <li>
                        <img src="/static/images/user.png" class="avatar" alt="Avatar">
                      </li>
                      <li>
                        <img src="/static/images/user.png" class="avatar" alt="Avatar">
                      </li> {% endcomment %}

                    </ul>
                  </td>
                  <td class="project_progress">
                    <div class="progress progress_sm">
                      <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="{{ t.PctComplete }}">
                      </div>
                    </div>
                    <small>{{ t.PctComplete|floatformat:0 }}% Complete</small>
                  </td>
                  <td>
                    {% if t.Status == 'OG' %}
                    <button type="button" class="btn btn-success btn-xs">On-Going</button>
                    {% elif t.Status == 'PD' %}
                    <button type="button" class="btn btn-success btn-xs">Pending</button>
                    {% else %}
                    <button type="button" class="btn btn-success btn-xs">Done</button>
                    {% endif %}
                  </td>
                  <td>
                    <a href="#" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i> Edit </a>
                    <a href="#" class="btn btn-success btn-xs"><i class="fa fa-line-chart"></i>
                      Update Progress
                    </a>
                    <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                  </td>
                </tr>

                {% comment %} {% endfor %} {% endcomment %}
                {% endfor %}
              </tbody>
            </table>
            <!-- end project list -->
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% endblock content %}

  {% block javascripts %}
  {{ block.super }}
  <!-- morris.js -->
  <script src="/static/vendors/raphael/raphael.min.js"></script>
  <script src="/static/vendors/morris.js/morris.min.js"></script>
  {% endblock javascripts %}

templates/sidebar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'home' %}" class="site_title"><i class="fa fa-spinner"></i> <span>ActOS | CKS</span></a>
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
    {% comment %} <div class="profile_pic">
      <img src="/static/images/img.jpg" alt="..." class="img-circle profile_img">
    </div> {% endcomment %}
    <div class="profile_info">
      <span>
        <h2>Activity Online Sheet</h2>
      </span>
      <h4>
        {{fname}}
        {{lname}}
      </h4>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>Log Your Activity Now</h3>
      <ul class="nav side-menu">
        <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Home </a>
        </li>
        <li><a><i class="fa fa-edit"></i> Activity Log <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="/ActOS/InputAct">Input Activity</a></li>
            <li><a href="{% url 'Core:activity_index' %}">View Activity</a></li>
            <li><a href="/ActOS/approve_activity.html">Approve Activity Sheet</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-desktop"></i> Projects <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'Core:project_index' %}">Project Administration</a></li>
            <li><a href="{% url 'Core:task_index' %}">Task Administration</a></li>
            <li><a href="{% url 'Core:assignment_index' %}">Personnel Assignment</a></li>
          </ul>
        </li>
        <li><a><i class="fa fa-bar-chart-o"></i> Monitoring Dashboard <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="/ActOS/tables.html">Monitor Project Progress</a></li>
            <li><a href="/ActOS/tables_dynamic.html">Monitor Project Allowance</a></li>
          </ul>
        </li>
      </ul>
    </div>

  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->

  <!-- /menu footer buttons -->
</div>

templates/top_navigation.html
{% load static %}
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          {% comment %} <img src="{% static 'images/img.jpg' %}" alt=""> {% endcomment %}
          {{fname}}
          {{lname}}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          <li><a href="/logout/"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>

      <li role="presentation" class="dropdown">
        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
          <i class="fa fa-envelope-o"></i>
          <span class="badge bg-green">6</span>
        </a>
        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
          <li>
            <a>
              <span class="image"><img src="{% static 'images/img.jpg' %}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="{% static 'images/img.jpg' %}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="{% static 'images/img.jpg' %}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <a>
              <span class="image"><img src="{% static 'images/img.jpg' %}" alt="Profile Image" /></span>
              <span>
                <span>John Doe</span>
                <span class="time">3 mins ago</span>
              </span>
              <span class="message">
                Film festivals used to be do-or-die moments for movie makers. They were where...
              </span>
            </a>
          </li>
          <li>
            <div class="text-center">
              <a>
                <strong>See All Alerts</strong>
                <i class="fa fa-angle-right"></i>
              </a>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
</div>